development:
  adapter: postgresql
  encoding: unicode
  database: archy_development
  pool: 5
  username: georgi
  password: toor

test:
  adapter: postgresql
  encoding: unicode
  database: archy_test
  pool: 5
  username: georgi
  password: toor